name: Prepare local environment
description: Prepare local environment for development by setup node, patch hosts file, and cache dependencies
outputs:
  cache-hit:
    description: Whether the dependencies were cached
    value: ${{ steps.npm-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Read .nvmrc
      shell: bash
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - name: Get npm cache directory
      shell: bash
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: npm-cache
      with:
        path: |
          **/node_modules
          ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
